update jenkin file

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -4,6 +4,7 @@ pipeline {
         stage('Build Docker Image') {
             steps {
                 script {
+                    // Kiểm tra xem Docker image đã tồn tại chưa
                     def imageExists = sh(script: "docker images -q elastalert:latest", returnStatus: true) == 0
                     if (!imageExists) {
                         echo 'Image not found locally. Building...'
@@ -22,55 +23,26 @@ pipeline {
                         sh 'kubectl rollout status deployment/elastalert'
                     }
                 }
+            }
+            post {
+                failure {
+                    echo 'Failed'
+                }
+            }
         }
     }
-    //     stage('Deploy') {
-    //         steps {
-    //             script {
-    //                 sh '''
-    //                     docker run -d --name elastalert-container \
-    //                     -v $(pwd)/config.yaml:/app/config.yaml \
-    //                     -v $(pwd)/rules:/app/rules \
-    //                     elastalert:latest
-    //                 '''
-    //             }
-    //         }
-    //     }
-    // }
     post {
         always {
             script {
-                sh 'docker stop elastalert-container || true'
-                sh 'docker rm elastalert-container || true'
+                sh '''
+                    if [ "$(docker ps -q -f name=elastalert-container)" ]; then
+                        docker stop elastalert-container || true
+                    fi
+                    if [ "$(docker ps -aq -f status=exited -f name=elastalert-container)" ]; then
+                        docker rm elastalert-container || true
+                    fi
+                '''
             }
         }
     }
 }
-}
-
-// pipeline {
-//     agent any
-//     stages {
-//         stage('Setup Environment') {
-//             steps {
-//                 sh 'python3.8 -m venv venv'
-//                 sh './venv/bin/pip install --no-index --find-links=vendor/ -r requirements.txt --use-pep517'
-//             }
-//         }
-//         // stage('Test') {
-//         //     steps {
-//         //         sh './venv/bin/python -m unittest discover'
-//         //     }
-//         // }
-//         stage('Deploy') {
-//             steps {
-//                 sh 'nohup ./venv/bin/python3.8 -m elastalert.elastalert --config config.yaml --verbose > elastalert.log 2>&1 &'
-//             }
-//         }
-//     }
-//     post {
-//         always {
-//             sh 'rm -rf venv'
-//         }
-//     }
-// }
